apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: phonebook
spec:
  selector:
    name: phonebook
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-phonebook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: phonebook
  template:
    metadata:
      labels:
        name: phonebook

    spec:
      containers:
      - image: mysql:5.7
        name: phonebook
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: db-secret
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: pv-claim
