apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  type: NodePort
  selector:
    name: search
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30300

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: search
  template:
    metadata:
      labels:
        name: search
    spec:
      containers:
      - name: search
        image: rknktm/search
        ports:
        - containerPort: 80
        # env:
        # - name: MYSQL_DATABASE_HOST
        #   value: mysql-service
        # - name: MYSQL_DATABASE
        #   value: phonebook
        # - name: MYSQL_USER
        #   value: rkn
        # - name: MYSQL_PASSWORD
        #   value: "123456789"
        envFrom:
        - configMapRef:
            name: my-config
        - secretRef:
            name: web-secret